dataset: 'munich'
data_root: './data/munich/'  
num_classes: 2  
split_ratio: [0.7, 0.1, 0.2]  

epochs: 100
batch_size: 16  
val_batch_size: 8
lr: 1e-3  ）
loss_lr: 1e-4  
weight_decay: 5e-4
anneal_cycle: 5000  
min_lr: 1e-6  
seed: 42  
log_interval: 
save_path: './checkpoints/munich/'  

stack_depth: 3  
iou_threshold: 0.5 
